
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pj_cdtn
    username: postgres
    password: 0
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ecommercedemo47@gmail.com
    password: kjiretscnvezdtql
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
#swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
#https://developer.paypal.com/dashboard/applications/edit/SB:QVdEcUFUQUVLR0QxUHdLTjd1VFBJQmxHOTRreTZZamZpRDZjZUpSSlQ1Y2NpTTRrdlYzVWZmNG1ZcXA0WnJVYVJSMFJXWUJuSXhvckhmZFo=
payment:
  paypal:
    clientId: AWDqATAEKGD1PwKN7uTPIBlG94ky6YjfiD6ceJRJT5cciM4kvV3Uff4mYqp4ZrUaRR0RWYBnIxorHfdZ
    clientSecret: EJ7H7aISC64EoFOOI1eqGg8wPSRLs7C2w5upPCsN-3Ftd27zJFbCPo_-K__VgHp5e0GXWCmiNG75P-P7
    mode: sandbox
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: 58X4B4HP
    secretKey: VRLDWNVWDNPCOEPBZUTWSEDQAGXJCNGZ
    returnUrl: http://localhost:8080/api/v1/payments/vn-pay-callback
    version: 2.1.0
    command: pay
    orderType: other

chatbot:
  secretkey: sk-None-bA9JWfwbSE2gRZFDz3aIT3BlbkFJBVKu04LpwDw4fvMisbGN
  secretkey_0: sk-None-TIAZ4qcVfJ4stlNb74YzT3BlbkFJL8P9wqA9bbp9V0Em6ynI
  secretkey_1: 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
  secretkey_2: sk-proj-ZqNUKpLmDcBYAU4AojvzT3BlbkFJMBJ737FBkdBlTTZCwGwd